config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'venues#index'
  get '/dashboard', to: 'pages#dashboard', as: :dashboard

  resources :venues, only: [:show, :create, :new, :edit, :update, :destroy] do
    resources :bookings, only: [:create]
  end
  resources :bookings, only: [:destroy, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  attr_accessor :duration
  belongs_to :user
  belongs_to :venue

  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :total_price, presence: true

  enum status: {
    pending: 0,
    active: 1,
    archived: 2
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  has_many :venues, dependent: :destroy
  has_many :bookings, dependent: :destroy
end

app/models/venue.rb
class Venue < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :bookings, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true
  validates :location, presence: true
  validates :price_per_hour, presence: true
  validates :room_size, presence: true, inclusion: { in: %w(Small Medium Large Extra-Large Stadium)}

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  private

  def skip_pundit?
    devise_controller?
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @venue = Venue.find(params[:venue_id])
    @booking = Booking.new(booking_params)
    authorize @booking
    @booking.user = current_user
    @booking.venue = @venue
    @booking.total_price = @venue.price_per_hour * @booking.duration.to_i
    @booking.end_time = @booking.start_time + @booking.duration.to_i.hours
    @booking.song_url.match?(/(?<==).*/) && @booking.song_url = @booking.song_url.match(/(?<==).*/)[0]
    @booking.save
    redirect_to dashboard_path
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.destroy
    redirect_to dashboard_path
  end

  def update
    @booking = Booking.find(params[:id])
    authorize @booking

    if params[:status] == 'active'
      @booking.active!
    elsif params[:status] == 'archived'
      @booking.archived!
    end
    respond_to do |format|
      format.html { redirect_to dashboard_path }
      format.json
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_time, :duration, :song_url)
  end

  def update_params
    params.require(:status).permit(:active, :archived)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def dashboard
    @bookings = current_user.bookings
    authorize @bookings
    @venues = current_user.venues
    @venue_bookings = Booking.where(venue: current_user.venues)
    # current_user.venues.each { |venue| venue.bookings.each { |booking| @venue_bookings << booking } }
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      sql_query = " \
        venues.name ILIKE :query \
        OR venues.description ILIKE :query \
        OR venues.location ILIKE :query \
      "
      @venues = Venue.where(sql_query, query: "%#{params[:query]}%")
    else
      @venues = Venue.all
    end

    @markers = @venues.geocoded.map do |venue|
      {
        lat: venue.latitude,
        lng: venue.longitude,
        info_window: render_to_string(partial: "info_window", locals: { venue: venue }),
        map_marker: render_to_string(partial: "map_marker", locals: { venue: venue }),
        # image_url: @venue.picture_url || "https://res.cloudinary.com/hwalk1/image/upload/v1654148153/#{Rails.env}/#{@venue.photo.key}.jpg"
      }
    end
  end

  def show
    @venue = Venue.find(params[:id])
    @booking = Booking.new
    authorize @venue

    @markers =
      [{
        lat: @venue.latitude,
        lng: @venue.longitude,
        info_window: render_to_string(partial: "info_window", locals: { venue: @venue }),
        map_marker: render_to_string(partial: "map_marker", locals: { venue: @venue }),
        # image_url: @venue.picture_url || "https://res.cloudinary.com/hwalk1/image/upload/v1654148153/#{Rails.env}/#{@venue.photo.key}.jpg"
      }]
  end

  def new
    @venue = Venue.new
    authorize @venue
  end

  def create
    @venue = Venue.new(venue_params)
    authorize @venue
    @venue.user = current_user
    if @venue.save
      redirect_to venue_path(@venue), notice: "Successfully created a venue"
    else
      render :new
    end

  end

  def edit
    @venue = Venue.find(params[:id])
    authorize @venue

  end

  def update
    @venue = Venue.find(params[:id])
    authorize @venue
    if @venue.update(venue_params)
      redirect_to venue_path(@venue), notice: "Successfully updated a venue"
    else
      render :new
    end
  end

  def destroy
    @venue = Venue.find(params[:id])
    authorize @venue
    @venue.destroy
  end


  private

  def venue_params
    params.require(:venue).permit(:name, :description, :location, :price_per_hour, :room_size, :photo) #Says look inside params, look for a key restaurant and permit categories.
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_banner.html.erb
<div class="container-fluid scroll w-100 p-0"> <%# fixed-top can be added%>
  <div class="banner">
    <div class="row">
      <div class="d-flex col-sm align-items-center">
        <h4 class="text-white m-0">
          Welcome To GigFox!
        </h4>
        <%# <form>
          <label for="date">Date: </label>
          <input type="text" id="date" name="date" placeholder="DD/MM/YYYY">
          <label for="location">Location: </label>
          <input type="text" id="location" name="location" placeholder="Melbourne">
          <label for="price-range">Price Range: </label>
          <input type="text" id="price-range" name="price-range" placeholder="from $100">
          <input type="submit" value="Go!">
        </form> %>
      </div>
    </div>
  </div>
</div>

<div class="top-venues">
<h1>Our Top Venues :</h1>
</div>

app/views/layouts/_cards.html.erb
<head>
  <link href=”https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css” rel=”stylesheet” integrity=”sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU” crossorigin=”anonymous”>
  <%# <meta name="viewport" content="width=device-width, initial-scale=1.0"> %>
</head>
<div class="container">
  <div class="row">
    <div class="home-container">
      <% @venues.each do |venue| %>
        <div class="card home">
           <% if defined?venue.photo.key%>
            <%= cl_image_tag venue.photo.key, class: "card-img-top" %>
            <%else%>
            <img class="card-img-top" src="<%= venue.picture_url %>" alt="Card image">
            <% end %>
          <div class="card-body text-center">
            <div class="card-info d-flex flex-column justify-content-between">
              <h4 class="card-title"><strong><%= venue.name %></strong></h4>


                <%# <div class="small-stars fs-5 text-primary">
                 <i class="fa fa-star"></i>
                 <i class="fa fa-star"></i>
                 <i class="fa fa-star"></i>
                 <i class="fa fa-star"></i>
                 <i class="fa fa-star"></i>
                </div> %>

              <p class="card-details"><%= venue.description %></p>
              <div class="d-flex justify-content-around">
                <div>
                  <i class="fa-solid fa-people-group"></i>
                  <p class="card-size"><%= venue.room_size %></p>
                </div>
                <div>
                  <i class="fa-solid fa-dollar-sign"></i>
                  <p class="card-price"><%= venue.price_per_hour %></p>
                </div>
                <%# <i class="fa-solid fa-location-dot"></i> %>
              </div>
            </div>
            <%= link_to 'Book Now', venue_path(venue), class:"btn book stretched-link w-100" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_expanded.html.erb
<head>
  <link href=”https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css” rel=”stylesheet” integrity=”sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU” crossorigin=”anonymous”>
  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
</head>

<div class="container" data-controller="total-cost" data-total-cost-price-value = "<%= @venue.price_per_hour.to_i %>">
  <div class="row gx-5">
    <div class="card col-7 gx-0">
      <div class="row">
       <% if defined?@venue.photo.key%>
          <%= cl_image_tag @venue.photo.key, class: "card-img-top expanded" %>
          <%else%>
          <img class="card-img-top expanded" src="<%= @venue.picture_url %>" alt="Card image">
          <% end %>
        <div class="expanded-card text-center">
          <div class="d-flex flex-column justify-content-between">
            <h1><%= @venue.name %></h1>
            <%# description %>
            <p><i class="fa-solid fa-asterisk"></i>&nbsp;<%= @venue.description %></p>
            <div class="info d-flex justify-content-around" style="margin: 20px;background: #ededed;border-radius: 10px;border: 1px solid #dbdbdb;">
              <div class="col-4 p-3">
                <%# price %>
                <div class="icon">
                  <i class="fa-solid fa-dollar-sign"></i>
                </div>
                <p><%= @venue.price_per_hour.to_s %></p>
              </div>
              <div class="col-4 p-3">
                <%# location %>
                <div class="icon">
                  <i class="fa-solid fa-location-dot"></i>
                </div>
                <p><%= @venue.location %></p>
              </div>
              <div class="col-4 p-3">
                <%# size %>
                <div class="icon">
                  <i class="fa-solid fa-people-group"></i>
                </div>
                <p><%= @venue.room_size %></p>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
    <div class="col-5">
      <div class="book-now">
        <div class="row">
          <div class="card p-3">
            <h1 class="text-center">Book Now</h1>
            <%= simple_form_for [ @venue, @booking ] do |f| %>
              <%= f.input :start_time, as: :string, input_html: {class: "datepicker search", data: { controller: 'flatpickr'}} %>
              <%= f.input :duration, collection: 1..24, include_blank: false, input_html: { data: {action: "change->total-cost#showTotal"}} %>
              <p >Total: <span data-total-cost-target="price"></span></p>
              <%= f.input :song_url %>
              <%= f.submit "Submit Booking", class: "btn w-100" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>


  </div>
</div>
<%# can be added for tags %>

<%# <div class="row">
  <div class="col-10 card gy-5">
  <h1>Related Venues</h1>
    <div class="row justify-content-center">
      <div class="col-3 card">
        <p>tag</p>
      </div>

      <div class="col-3 card">
        <p>tag</p>
      </div>

      <div class="col-3 card">
        <p>tag</p>
      </div>

      <div class="col-3 card">
        <p>tag</p>
      </div>

    </div>
    </div>
  </div>
</div> %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top"> <%# fixed-top%>
  <div class="container-fluid justify-content-between">
    <%= link_to root_path, class:"navbar-brand" do %>
      <%= image_tag 'welcome-fox-1.png', height:80  %>
    <% end %>

    <%= form_tag root_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "search-bar form-control-search datepicker ps-3",
        placeholder: "Find a Venue"
      %>
      <button class="btn">
        <i class="fa-solid fa-magnifying-glass"></i>
        <%# <%= button_tag type:'submit', class: "btn" %>
      </button>
    <% end %>

    <%# <div class="venue-owner" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <li><%= link_to 'Venue Owner?', dashboard_path, class: 'nav-link' %>
        <%# </li> %>
      <%# </ul> %>
    <%# </div> %>
    <div class="dropdown">
      <% if user_signed_in? %>
        <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
          My Profile
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
          <li><%= link_to 'My Dashboard', dashboard_path, class: 'dropdown-item' %></li>
          <li><%= link_to 'Create a Venue', new_venue_path, class: 'dropdown-item' %></li>
          <li><%= link_to 'My Settings', edit_user_registration_path, class: 'dropdown-item' %></li>
          <li><%= link_to 'Log Out', destroy_user_session_path, class: 'dropdown-item', method: 'delete' %></li>
        </ul>
      <% else %>
        <%= link_to 'Sign In', new_user_session_path, class:"btn" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gigfox</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body class="padd"> <%# located in expanded.scss %>
    <%= render "layouts/navbar" %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <script src="https://kit.fontawesome.com/7b8fdf30c4.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/_booking.html.erb
<div class="shadow rounded d-flex card-booking my-4">

    <% if defined? booking.venue.photo.key%>
            <%= cl_image_tag booking.venue.photo.key, class: "img-booking rounded-start", height: "150px", width: "150px"  %>
          <%else%>
            <img class="img-booking rounded-start" src="<%= booking.venue.picture_url%>" alt="venue image" height="150px" width="150px">
          <% end %>
  <div class="p-2 d-flex flex-column align-items-center justify-content-around">
    <h4><%= booking.venue.name %></h4>
    <p class="text-secondary"><%= booking.venue.location %></p>
    <p><b>Total Cost: $<%= booking.total_price %></b></p>
    <p><b><%= booking.start_time.strftime("%a, %-d %b %l%P") %> -<%= booking.end_time.strftime("%l%P") %></b></p>
    <% unless booking.song_url == ''%>
    <iframe width="200" height="50" src="https://www.youtube.com/embed/<%= booking.song_url %>?fs=0&modestbranding=1" title="YouTube video player" frameborder="0"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"></iframe>
    <% end %>
      <%= link_to booking_path(booking),
      method: :delete,
      data: { confirm: "Are you sure?" } do %>
      <i class="fa-solid fa-trash"></i>
      <% end %>
  </div>
</div>

app/views/pages/_bookings.html.erb
<div class="row">
  <div class="col-4">
    <h3>Pending</h3>
    <% @bookings.each do |booking| %>
      <% if booking.status == 'pending' %>
        <%= render 'booking', booking: booking %>
      <% end %>
    <% end %>
  </div>

  <div class="col-4">
    <h3>Accepted</h3>
    <% @bookings.each do |booking| %>
      <% if booking.status == 'active' %>
        <%= render 'booking', booking: booking %>
      <% end %>
    <% end %>
  </div>

  <div class="col-4">
    <h3>Declined</h3>
    <% @bookings.each do |booking| %>
      <% if booking.status == 'archived' %>
        <%= render 'booking', booking: booking %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/pages/_pending_booking.html.erb
<div class="shadow rounded d-flex card-booking my-4" data-controller="accept-decline-booking" data-accept-decline-booking-target="card">
  <% if defined? booking.venue.photo.key%>
            <%= cl_image_tag booking.venue.photo.key, class: "img-booking rounded-start", height: "150px", width: "150px"  %>
          <%else%>
            <img class="img-booking rounded-start" src="<%= booking.venue.picture_url%>" alt="venue image" height="150px" width="150px">
          <% end %>
  <div class="p-2 d-flex flex-column align-items-center justify-content-around">
    <h4><%= booking.venue.name %></h4>
    <p class="text-secondary"><%= booking.venue.location %></p>
    <p><b>Total Cost: $<%= booking.total_price %></b></p>
    <p><b><%= booking.start_time.strftime("%a, %-d %b %l%P") %> -<%= booking.end_time.strftime("%l%P") %></b></p>
    <% unless booking.song_url == ''%>
    <iframe width="200" height="50" src="https://www.youtube.com/embed/<%= booking.song_url %>?fs=0&modestbranding=1" title="YouTube video player" frameborder="0"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"></iframe>
    <% end %>
    <div class="d-flex">
      <%= simple_form_for booking, data: { action: "submit->accept-decline-booking#send"} do |f|%>
        <input type="hidden" name="status" value="active" autocomplete="off">
        <button class="icon icon-accept me-4"><i class="fa-solid fa-check"></i></button>
      <% end %>

      <%= simple_form_for booking, data: { action: "submit->accept-decline-booking#send"} do |f|%>
        <input type="hidden" name="status" value="archived" autocomplete="off">
        <button class="icon icon-decline"><i class="fa-solid fa-xmark"></i></button>
      <% end %>
    </div>
      <%= link_to booking_path(booking),
      method: :delete,
      data: { confirm: "Are you sure?" } do %>
      <i class="fa-solid fa-trash"></i>
      <% end %>
  </div>
</div>

app/views/pages/_venue_bookings.html.erb
<div class="row">
  <div class="col-4 text-center">
    <h3>Pending</h3>
    <% @venue_bookings.each do |booking| %>
      <% if booking.status == 'pending' %>
        <%= render 'pending_booking', booking: booking %>
      <% end %>
    <% end %>
  </div>

  <div class="col-4" >
    <h3>Accepted</h3>
    <div id="accepted">
      <% @venue_bookings.where(status: "active").each do |booking| %>
        <%= render 'booking', booking: booking %>
      <% end %>
    </div>
  </div>

  <div class="col-4">
    <h3>Declined</h3>
    <div id="declined">
      <% @venue_bookings.where(status: 'archived').each do |booking| %>
        <%= render 'booking', booking: booking %>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/_venues.html.erb
<div class="row justify-content-center">

 <% @venues.each do |venue| %>
        <div class="card col-4 p-0 m-2">
           <% if defined? venue.photo.key%>
            <%= cl_image_tag venue.photo.key, class: "card-img-top" %>
          <%else%>
            <img class="card-img-top" src="<%= venue.picture_url %>" alt="Card image">
          <% end %>

          <div class="card-body">
            <h5 class="card-title"><%= venue.name %></h5>
            <p class="card-details"><%= venue.description %></p>
            <p class="card-details">Room Size: <%= venue.room_size %></p>
            <p class="card-price">$<%= venue.price_per_hour %></p>

            <%= link_to edit_venue_path(venue),
            class:"btn edit" do %>
              <i class="fa-solid fa-pen-to-square"></i>
            <% end %>

            <%= link_to venue_path(venue),
            class:"btn",
            method: :delete,
	          data: { confirm: "Are you sure?" } do %>
              <i class="fa-solid fa-trash"></i>
            <% end  %>

          </div>
        </div>
      <% end %>

</div>

app/views/pages/dashboard.html.erb
<div class="box-container">
 <div class="container text-center">
  <h1 class="text-center pb-5"><i>Welcome back,</i> <%= current_user.name %></h1>


<div class="span12 text-center">
  <ul class="nav nav-pills center-pills" id="tab" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link active" id="bookings-tab" data-bs-toggle="pill" data-bs-target="#bookings" type="button" role="tab" aria-controls="bookings" aria-selected="true">My Bookings</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="venues-tab" data-bs-toggle="pill" data-bs-target="#venues" type="button" role="tab" aria-controls="venues" aria-selected="false">My Venues</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="venue-bookings-tab" data-bs-toggle="pill" data-bs-target="#venue-bookings" type="button" role="tab" aria-controls="venue-bookings" aria-selected="false">Venue Bookings</button>
    </li>
  </ul>
  </div>

  <div class="tab-content" id="tabContent">
    <div class="tab-pane fade show active" id="bookings" role="tabpanel" aria-labelledby="home-tab">
        <%= render 'bookings' %>
    </div>
    <div class="tab-pane fade" id="venues" role="tabpanel" aria-labelledby="venues-tab">
        <%= render 'venues' %>
    </div>
    <div class="tab-pane fade" id="venue-bookings" role="tabpanel" aria-labelledby="venue-bookings-tab">
        <%= render 'venue_bookings' %>
    </div>
  </div>
 </div>
</div>

app/views/venues/_form.html.erb
<div class = "container" data-controller="geocoder" >
  <%= simple_form_for(@venue) do |f| %>
    <%= f.input :name %>
    <%= f.input :description, as: :text %>
    <%= f.input :location,
                input_html: { data: { geocoder_target: "location" }, class: "d-none"},
                wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } } %>
    <%= f.input :price_per_hour %>
    <%= f.input :room_size, collection: %w(Small Medium Large Extra-Large Stadium)%>
    <%= f.input :photo, as: :file %>
    <%= f.submit class: "btn" %>
  <% end %>
</div>

app/views/venues/_index_map.html.erb
<div
  class="map pe-none d-flex align-items-center"
  id="index-map-container"
  data-controller="toggle-visibility"
>
  <div class="container">
      <div style="width: 100%; height: 800px;"
        data-controller="mapbox"
        class="opacity-0"
        data-toggle-visibility-target="element"
        data-mapbox-markers-value="<%= @markers.to_json %>"
        data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
  </div>

  <button data-action="click->toggle-visibility#toggle" class="pe-auto btn btn-index-map" style="">Show Map</button>

</div>

app/views/venues/_info_window.html.erb
<h2><%= venue.name %></h2>
<p><%= venue.location %></p>
<p>Price: <%= venue.price_per_hour %>/h</p>
<%= link_to 'Book Now', venue_path(venue), class:"btn" %>

app/views/venues/_map.html.erb
<div class="container map">
  <div class="row">
    <div class="col-12">
      <div style="width: 100%; height: 600px;"
        data-controller="mapbox"
        data-mapbox-markers-value="<%= @markers.to_json %>"
        data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

app/views/venues/_map_marker.html.erb
<% image_url = venue.photo.attached? ? cl_image_path(venue.photo.key) : venue.picture_url %>
<div class = "mapmarker" style = "background-image: url(<%= image_url %>) "></div>

app/views/venues/edit.html.erb
<div class = "container">
  <h1 style = 'text-align: center'>Edit</h1>
  <%= render 'form' %>
</div>

app/views/venues/index.html.erb
<%= render "layouts/banner" %>
<%= render 'layouts/cards' %>
<%= render 'index_map' %>

app/views/venues/new.html.erb
<div class = "container" data-controller="geocoder" >
  <%= simple_form_for(@venue) do |f| %>
    <%= f.input :name %>
    <%= f.input :description, as: :text %>
    <%= f.input :location,
                input_html: { data: { geocoder_target: "location" }, class: "d-none"},
                wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } } %>
    <%= f.input :price_per_hour %>
    <%= f.input :room_size, collection: %w(Small Medium Large Extra-Large Stadium)%>
    <%= f.input :photo, as: :file %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>
</div>

app/views/venues/show.html.erb
<%= render "layouts/expanded" %>
<%= render 'map' %>